no-gui: "&4That gui does not exist!"
#checks to see if you are using the version spigot, if you have a custom version name change this
#used to check the value for bungee, change this to "bungee" if you want to force bungee or "redis" if you want to force redis.
version: "spigot"
servers:
- "prison"

#remote-guis:
#  remote:
#    file-name: "remote.yml"
#    url: "https://raw.githubusercontent.com/ClubObsidian/DynamicGUIExamples/master/examples/remote.yml"