name: DynamicGui
main: com.clubobsidian.dynamicgui.plugin.bukkit.BukkitPlugin
version: ${pluginVersion}
author: VirusTotal
api-version: 1.13
softdepend: [Vault, PlaceholderAPI, RedisBungee, PlayerPoints, Citizens, Rankup, Foundry]
commands:
  gui:
    description: "DynamicGUI gui command!"
  guilist:
    description: "Lists out all the guis for DynamicGUI!"
  dynamicgui:
    descriptions: "Command for handling management of DynamicGui guis"
    aliases: ["dyngui"]