name: DynamicGui
main: com.clubobsidian.dynamicgui.plugin.bukkit.BukkitPlugin
version: 0.0.1
author: VirusTotal
softdepend: [Vault, PlaceholderAPI, RedisBungee, PlayerPoints, Citizens, Rankup]
commands:
  gui:
    description: "DynamicGUI gui command!"
  guilist:
    description: "Lists out all the guis for DynamicGUI!"
  dynamicgui:
    descriptions: "Command for handling management of DynamicGui guis"