name: DynamicGui
main: com.clubobsidian.dynamicgui.bukkit.plugin.BukkitPlugin
version: ${pluginVersion}
author: VirusTotal
api-version: 1.13
softdepend: [Vault, PlaceholderAPI, RedisBungee, PlayerPoints, Citizens, Rankup, Foundry, Oraxen, ItemsAdder]