plugins {
    id 'java-library'
    id("io.papermc.paperweight.userdev") version "2.0.0-beta.19"
}

processResources {
    filesMatching('plugin.yml') {
        expand 'pluginVersion': project.version
    }
}

shadowJar {
    archiveBaseName.set('DynamicGui-Bukkit')
    archiveClassifier.set('')
    assemble {
        dependsOn tasks.named("shadowJar")
    }
}

//tasks.shadowJar.mustRunAfter ':core:shadowJar'

dependencies {
    implementation project(path: ':core')
    compileOnly 'com.github.clubobsidian:foundry:3.0.0'
    paperweight.paperDevBundle("1.21.11-R0.1-SNAPSHOT")
    implementation "org.incendo:cloud-paper:2.0.0-beta.10"
}